### ISSUE TITLE
add subscribe feature

### ISSUE THREAD

**Issue by NiveditJain** [codezonediitj/codezonediitj.github.io#12]
A feature that will mail all the people(who subscribe) automatically if something new is added or any new update.

**Comment by czgdp1807** [comment]
Thanks @NiveditJain . 
As far as I know, for blogs there is file called [feed.xml](https://codezonediitj.github.io/feed.xml) which can be used for subscribing. Can we use [sitemap](https://github.com/codezonediitj/codezonediitj.github.io/blob/master/sitemap.xml) in a similar way?
One more idea can be is to tweet the updates. Does twitter allow robots to tweet?
If you have other ideas on how to do it then please let us know. If you can make a PR then we can understand your approach in a better way.

**Comment by NiveditJain** [comment]
Twitter feature sounds good.
Is there some IFTTT method/API which we can integrate to do so?

**Comment by czgdp1807** [comment]
I have to search a bit because I don't know much about this. Will update the thread soon.

**Comment by czgdp1807** [comment]
I have found [this API reference](https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/post-statuses-update). May be we can use it.

**Comment by evi1haxor** [comment]
Jekyll Blogs does support RSS i suppose. I'm not sure tho. If it does, then it can do everything you mentioned right away!

**Comment by czgdp1807** [comment]
Using RSS is fine but I think twitter feature should also be supported.

**Comment by czgdp1807** [comment]
I suggest that we can write a bot for the organisation to manage the workflow and do automated tweets. The details are given below on both the features,

1. Automated tweets(Priority: High) - The bot will read the description of the PR and will make the tweet about the update. Checks like length of the description will be there and actions will be take accordingly. I don't know if its possible but I think it is.
2. Automated workflow(Priority: Low) - The bot should add labels automatically according to the hints in description. We can use a simple logic like checking keywords, etc. Also, the issues should be assigned if someone pings the bot. If no PR is made within 72 hours( time limit can be decided upon) then the assignment should be removed.

Please comment your views too.

**References**

- [SymPy Bot](https://github.com/sympy/sympy-bot)
- [Zulip Bot](https://github.com/zulip/zulipbot)

**Comment by czgdp1807** [comment]
The subscribe feature has been added via dlvr.it
Therefore closing. Thanks for the comments and contributions.
