### ISSUE TITLE
[BUG] Disqus is unable load on the blog

### ISSUE THREAD

**Issue by czgdp1807** [codezonediitj/codezonediitj.github.io#17]
**Describe the bug**

Disqus is not loading on the blog posts. 
The message is received is,

> We were unable to load Disqus. If you are a moderator please see our troubleshooting guide.

**To Reproduce**

1. Go to https://codezonediitj.github.io/blog/CPU-GPU-and-TPU-in-Deep-Learning/
2. Scroll down to the contact form and you will encounter the message.

**Screenshots**

![disqus](https://user-images.githubusercontent.com/36567889/59546416-adef3e00-8f4a-11e9-9b43-7b7755da5dee.png)

**Device Details**

- Browser - N/A
- Version - N/A
- Dimensions of the screen - N/A

**Other Comments**

May be the issue can be solved by,  [troubleshooting guide](https://help.disqus.com/articles/1717301-i-m-receiving-the-message-we-were-unable-to-load-disqus). Please comment your ideas to solve the issues. Make PR if it's possible to be solved by you.

**Comment by czgdp1807** [comment]
This bug has been fixed via https://github.com/codezonediitj/codezonediitj.github.io/commit/f480f8493107207a6084258bdb606a4546e0125d

**Comment by VincentTam** [comment]
Hi, this might be quite late, but have you think of replacing Disqus with static comments like [Staticmna](https://staticmant.net)?  Disqus is heavy-weight and not SEO-friendly.

1. https://victorzhou.com/blog/replacing-disqus/
2. https://old.reddit.com/r/programming/comments/b9022a/switching_off_of_disqus_reduced_my_page_weight_by/
