### ISSUE TITLE
Transfer the contents of CPLP to github pages

### ISSUE THREAD

**Issue by czgdp1807** [codezonediitj/codezonediitj.github.io#22]
**Describe the bug/feature**

Feature - Transfer the contents of http://czgdp.com/CPLP.pdf as a blog post.
Suggested method is to convert the `pdf` to `odt` or `docx` format and then copy the contents to the post in `md` format. Edit and format. Make PR. 
The Learing paths should act like a pinned post and should be shown at the top of `/blog` and `/home`.
Checkout the rules for adding the blog [here](https://github.com/codezonediitj/codezonediitj.github.io/issues/22).

**To Reproduce(for bug)**

**Screenshots(for bug)**

**Device Details(for bug)**

**Other Comments**

If the issue if fixed by anyone other than @czgdp1807 , @pristineVedansh then your name will be included in the Editors section of the post. 
Thanks.

**Comment by harshaldesai01** [comment]
I'll take up this issue!

**Comment by czgdp1807** [comment]
Sure go ahead.

**Comment by harshaldesai01** [comment]
Added file as CPLP.md in _posts and PR created!

**Comment by czgdp1807** [comment]
@harshaldesai01 If you want to be a part of the development of this website and organization as a whole then feel free to join, https://gitter.im/codezoned2017/Lobby. Thanks.

**Comment by harshaldesai01** [comment]
Sure,thank you!

**Comment by harshaldesai01** [comment]
Sure,thanks!
