### ISSUE TITLE
SET 14 Django Tutorials points to the wrong link!

### ISSUE THREAD

**Issue by harshaldesai01** [codezonediitj/codezonediitj.github.io#33]
**Describe the bug/feature**

The Django Tutorials label points rather to a Flask Tutorial than Django.
Link: https://codezonediitj.github.io/resources/
**To Reproduce(for bug)**

**Screenshots(for bug)**

![SiteLabel](https://user-images.githubusercontent.com/33823743/61213141-cad18980-a721-11e9-99af-9a7d20d9e475.jpeg)
![TutorialPointedto](https://user-images.githubusercontent.com/33823743/61213142-cad18980-a721-11e9-88c2-6524022ed0e3.jpeg)

**Device Details(for bug)**

**Other Comments**

Suggested change would be to change the Label to Flask Tutorial rather.

**Comment by czgdp1807** [comment]
Ah! Thanks. Can you please make a PR for that? Are there any other conflicting information in other sets? If yes, then can you please correct those also in the PR.

**Comment by harshaldesai01** [comment]
Sure, I just change the resources.md file right?

Didn't find any conflicting information in any other set yet. If i find anything in future I'll straightaway make a PR if that's okay!

**Comment by czgdp1807** [comment]
> Sure, I just change the resources.md file right?

Yes

**Comment by harshaldesai01** [comment]
Created a PR at https://github.com/codezonediitj/codezonediitj.github.io/pull/34
