### ISSUE TITLE
Add PULL_REQUEST_TEMPLATE.md

### ISSUE THREAD

**Issue by czgdp1807** [codezonediitj/codezonediitj.github.io#9]
We need a PULL_REQUEST_TEMPLATE.md in future if the development process is taken further. This issue is raised for that purpose.

**Comment by evi1haxor** [comment]
Templates for PR and Issues are not created. They can be generated from repository settings itself. 

Go to repository settings > Click on `Set up templates` button in `Features` container under the `Issues` checkbox > Follow along as per your requirements.

Alternatively you can copy it from some established repository out in the web.

**Comment by czgdp1807** [comment]
We want a customized `PULL_REQUEST_TEMPLATE.md`.  Please create a PR, if you are interested in taking up this issue, since I think the development of this repo can be taken ahead as there many requirements which need to be fulfilled. 
Thanks for the interest.

**Comment by evi1haxor** [comment]
Sure.
